apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-mysql
spec:
  volumeName: event-data
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
