version: '3.9'
services:
  auth-service:
    env_file:
      - ../.env.prod
    build:
      context: ../
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    profiles:
      - production
    volumes:
      - auth-service-volume:/usr/src/app
    restart: always
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
volumes:
  auth-service-volume: