version: '3.9'
services:
  ticket-service:
    env_file:
      - ../.env.prod
    build:
      context: ../
      dockerfile: apps/ticket-service/Dockerfile
    container_name: ticket-service
    profiles:
      - production
    volumes:
      - ticket-service-volume:/usr/src/app
    restart: always
    ports:
      - ${TICKET_SERVICE_PORT}:${TICKET_SERVICE_PORT}
    depends_on:
      - ticket-service-db
  ticket-service-db:
    container_name: 'ticket-service-db'
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_USER}
      - MYSQL_TCP_PORT=${TICKET_SERVICE_DB_PORT}
    ports:
      - '${TICKET_SERVICE_DB_PORT}:${TICKET_SERVICE_DB_PORT}'
    volumes:
      - ticket-service-db-volume:/var/lib/mysql
volumes:
  ticket-service-db-volume:
  ticket-service-volume:
