apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-client
  labels:
    name: ticketforge
spec:
  ingressClassName: nginx
  rules:
  - host: ticketforge.broker.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rabbitmq-client
            port: 
              number: 15672
  - host: ticketforge.broker-stomp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rabbitmq-client
            port: 
              number: 15674