apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service-db
data:
  V1.0__initial_schema.sql: |
    create table `ticket_entity` (`id` varchar(255) not null, `created_at` datetime not null, `updated_at` datetime not null, `purchased_unit_price` int not null, `quantity` int not null, `user_id` varchar(255) not null, `event_id` varchar(255) not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;
