apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ticket-mysql
spec:
  volumeName: ticket-data
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
