apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
spec:
  selector:
    matchLabels:
      app: user-service-db
  template:
    metadata:
      labels:
        app: user-service-db
    spec:
      containers:
      - name: user-service-db
        image: mysql:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "1Gi"
            cpu: "250m"
        volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_ROOT_USER
            value: root
          - name: MYSQL_DATABASE
            value: ticketforge
        ports:
        - containerPort: 3306
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: user-mysql
