apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mysql
spec:
  volumeName: user-data
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
